version: '3'

services:
  app:
    build: . # faz o build a partir do diretório raiz onde se encontra o Dockerfile
    ports:
      - 3000:3000 # liga a porta 3000 da máquina local para a porta 3000 do container
    volumes:
      - .:/home/node/app # tudo que é feito na máquina local, quero que reflta no container
  db:
    image: bitnami/mongodb:5.0.17
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: nest
      
# vai ficar dentro das configurações de volume do docker
volumes:
  mongodb_data:
    driver: local
